Django/todo_2/addTodo/urls.py
from django.urls import path
from . import views
from .views import *


urlpatterns = [
    path("home",views.home,name="home"),
    path("register",RegisterUser.as_view(),name="register"),
    path("lists",views.seeList,name="lists"),
    path("addList",views.CreateTodoList.as_view(),name="addList"),
    path("addTask",views.CreateTodoTask.as_view(),name="addTask"),
    path("<str:todo_list_name>/tasks",views.seeTasks,name="tasks"),
    
    path("UpdateTodoList/<int:pk>",UpdateTodoList.as_view(),name="UpdateTodoList"),
    path("DeleteTodoList/<int:pk>/",DeleteTodoList.as_view(),name="DeleteTodoList"),
    
    path("UpdateTodoTask/<int:pk>/",UpdateTodoTask.as_view(),name="UpdateTodoTask"),
    path("DeleteTodoTask/<int:pk>/",DeleteTodoTask.as_view(),name="DeleteTodoTask"),
    
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/",LogoutUser.as_view(),name="logout"),
   
]

Django/todo_2/todo_2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/',include("addTodo.urls")),
]

Django/todo_2/addTodo/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
# Create your models here.
class ToDoList(models.Model):
      TASK_CODES = [
        ("JB","Job"),
        ("DL","Daily"),
        ("HB","Habit"),
        ("ED","Education"),
        ("HL","Holiday"),
    ]
      task_title = models.CharField(max_length=60)
      task_category = models.CharField(max_length=2,choices=TASK_CODES)
      
      def __str__(self) -> str:
           return self.task_title
    


class ToDoTask(models.Model):
    task_name = models.CharField(max_length=60)
    task_description = models.TextField(null=True,blank=True)
    task_complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    todo_list = models.ForeignKey(ToDoList,on_delete=models.CASCADE)
    
    def __str__(self) -> str:
         return self.task_name
    

class User(AbstractBaseUser):
  username = models.CharField(max_length=50,unique=True)
  email = models.EmailField(unique=True)
  password = models.CharField(max_length=100)
  phone = models.IntegerField(null=True,unique=True)
  address = models.CharField(max_length=150,null=True)
  
  
  USERNAME_FIELD = "username"
  REQUIRED_FIELDS = ["email"]
  
   
  
    
    

Django/todo_2/addTodo/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password'] 
    def init(self, args, **kwargs):
        super(RegistrationForm, self).init(args, **kwargs)
        
        

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

Django/todo_2/addTodo/views.py
from typing import Set
from django.contrib import messages
from django.shortcuts import render,redirect
from .forms import RegistrationForm
from django.views.generic.edit import UpdateView,DeleteView,CreateView
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import reverse,reverse_lazy
from .models import *
from .forms import *
from django.contrib.auth.hashers import make_password


# Create your views here.
def home(request):
    return render(request,'addTodo/home.html')

def seeList(request):
    queryset = ToDoList.objects.all()
    context = {'queryset': queryset}
    return render(request,'addTodo/lists.html',context)

class CreateTodoList(CreateView):
    model = ToDoList
    fields = ['task_title', 'task_category']
    template_name = 'addTodo/addList.html'
    success_url = reverse_lazy('lists')

    def form_valid(self, form):
        task_title = form.cleaned_data['task_title']
        
        if ToDoList.objects.filter(task_title=task_title).exists():
            form.add_error('task_title', 'A list with this title already exists.')
            return self.form_invalid(form)
    
        return super().form_valid(form)
    

class UpdateTodoList(UpdateView):
    model = ToDoList
    fields = ['task_title','task_category']
    template_name = 'addTodo/update_confirmation.html'
    success_url = reverse_lazy('lists')
    
    def form_valid(self, form):
        task_title = form.cleaned_data['task_title']
        
        if ToDoList.objects.filter(task_title=task_title).exists():
            form.add_error('task_title', 'A list with this title already exists.')
            return self.form_invalid(form)
    
        return super().form_valid(form)
    

class DeleteTodoList(DeleteView):
    model = ToDoList
    success_url = reverse_lazy('lists')
    template_name = 'addTodo/delete_confirmation.html'  

class CreateTodoTask(CreateView):
    model = ToDoTask
    fields = ['task_name','task_description','todo_list']
    template_name = "addTodo/addTask.html"
    def get_success_url(self) -> str:
        todo_list_name = self.object.todo_list.task_title
        return reverse('tasks', kwargs={'todo_list_name':todo_list_name})


class UpdateTodoTask(UpdateView):
    model = ToDoTask
    fields = ['task_name', 'task_description', 'todo_list']
    template_name = "addTodo/addTask.html"
    
    def get_success_url(self) -> str:
        todo_list_name = self.object.todo_list.task_title
        return reverse('tasks', kwargs={'todo_list_name':todo_list_name})



class DeleteTodoTask(DeleteView):
    model = ToDoTask
    success_url = reverse_lazy('lists')
    template_name = 'addTodo/delete_confirmation.html' 
     

    

#@login_required(login_url="/login")
def seeTasks(request, todo_list_name):
    todo_list = ToDoList.objects.get(task_title=todo_list_name)
    queryset = ToDoTask.objects.filter(todo_list=todo_list)
    context = {'queryset': queryset}
    return render(request, 'addTodo/tasks.html', context)

    

class RegisterUser(CreateView):
    form_class = RegistrationForm
    template_name = "addTodo/register.html"

    def form_valid(self, form):
        
        form.instance.password = make_password(form.cleaned_data['password'])
        
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("login")


class LoginUser(LoginView):
    template_name="addTodo/login.html"
    redirect_authenticated_user = True
    def get_success_url(self) -> str:
        print("Good")
        return reverse_lazy('lists')
    
    def form_invalid(self, form):
     print(form.errors)
     messages.error(self.request, "Invalid username or password")
     return self.render_to_response(self.get_context_data(form=form))
    
    
class LogoutUser(LogoutView):
    template_name = "addTodo/logout_confirm.html"
    redirect_field_name = "login"
    print("Logout")
    reverse_lazy("login")

Django/todo_2/addTodo/templates/addTodo/addList.html
{% extends 'addTodo/base.html' %}
{% block title %}Add List{% endblock %}


{% block content %}
<div class="row">
  <div class="col-md-6 mx-auto">
    <div class="card bg-dark">
      <div class="card-body">
        <h5 class="card-title">Add List</h5>
         <form method="post">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit" class="btn btn-primary">Save List</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Django/todo_2/addTodo/templates/addTodo/addTask.html
{% extends 'addTodo/base.html' %}
{% block title %}Add Task{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 mx-auto">
    <div class="card bg-dark">
      <div class="card-body">
        <h5 class="card-title">Add Task</h5>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Save Task</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Django/todo_2/addTodo/templates/addTodo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    {% include "addTodo/header.html" %}
    
        {% block content %}
        
        {% endblock %}
    </div>
    
    
</body>
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

Django/todo_2/addTodo/templates/addTodo/delete_confirmation.html
{% extends 'addTodo/base.html' %}
{% block title %}Delete Confirmation{% endblock %}

{% block content %}
  <h1>Confirm Delete</h1>
  <p>Are you sure you want to delete this task?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
    <a href="{% url 'lists' %}">Cancel</a>
  </form>
{% endblock %}

Django/todo_2/addTodo/templates/addTodo/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{%url "home"%}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url "register"%}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url "login"%}">Login</a>
      </li>
         <li class="nav-item">
        <a class="nav-link" href="{%url "lists"%}">Lists</a>
      </li>
     
         <li class="nav-item">
        <a class="nav-link" href="{%url "addList" %}">Add List</a>
      </li>
      
      </li>
     
         <li class="nav-item">
        <a class="nav-link" href="{%url "addTask"%}">Add Task</a>
      </li>

      </li>
     
         <li class="nav-item">
        <a class="nav-link"  href="{%url "logout"%}">Logout</a>
      </li>
     
    </ul>
  </div>
</nav>

Django/todo_2/addTodo/templates/addTodo/home.html
{% extends 'addTodo/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    

    <h1>Home</h1>
   
{% endblock %}

Django/todo_2/addTodo/templates/addTodo/lists.html
{% extends 'addTodo/base.html' %}
{% block title %}Lists{% endblock %}

{% block content %}
<div class="row">
  {% for item in queryset %}
  <div class="col-md-4 mb-4">
    <div class="card bg-dark">
      <div class="card-body">
        <h5 class="card-title">{{ item.task_title }}</h5>
        {%for task in item.todotask_set.all%}
        <p class="card-text">{{task.task_name}}</p>
        {%endfor%}
        <a class="btn btn-sm btn-info"href="{% url 'tasks' todo_list_name=item.task_title %}" class="card-link ">View Tasks</a>
        <a class="btn btn-sm btn-success"href="{% url 'UpdateTodoList' pk=item.pk %}" class="card-link">Update List</a>
        <a class="btn btn-sm btn-danger"href="{% url 'DeleteTodoList' pk=item.pk %}" class="card-link">Delete</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

Django/todo_2/addTodo/templates/addTodo/login.html
{% extends 'addTodo/base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
<h2>Login</h2>
<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>

{% endblock %}

Django/todo_2/addTodo/templates/addTodo/logout_confirm.html
{% extends 'addTodo/base.html' %}
{% block title %}Logout{% endblock %}

{% block content %}
<h2>Logout</h2>
<p>Are you sure you want to logout?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit">Logout</button>
</form>
{% endblock %}

Django/todo_2/addTodo/templates/addTodo/register.html
{% extends 'addTodo/base.html' %}
{% block title %}Register{% endblock %}

{% block content %}
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Registration Form</h3>
            <form method="post">
              {% csrf_token %}

              <div class="row mb-4">
                <div class="col">
                  <label class="form-label col-md-2" for="{{ form.username.id_for_label }}">Username</label>
                  {{ form.username }}
                </div>
              </div>

              <div class="row mb-4">
                <div class="col">
                  <label class="form-label col-md-2" for="{{ form.email.id_for_label }}">Email</label>
                  {{ form.email }}
                </div>
              </div>

              <div class="row mb-4">
                <div class="col">
                  <label class="form-label col-md-2" for="{{ form.password1.id_for_label }}">Password</label>
                  {{ form.password1 }}
                </div>
              </div>

              <div class="row mb-4">
                <div class="col">
                  <label class="form-label col-md-2" for="{{ form.password2.id_for_label }}">Confirm Password</label>
                  {{ form.password2 }}
                </div>
              </div>

              <div class="mt-4 pt-2">
                <input class="btn btn-primary btn-lg" type="submit" value="Register" />
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

Django/todo_2/addTodo/templates/addTodo/tasks.html
 {% extends 'addTodo/base.html' %}
{% block title %}Tasks{% endblock %}

{% block content %}
 <ul>
    {% for item in queryset %}
    <li>{{ item.task_name}}</li>
    <li>{{ item.task_description}}</li>
    <li>{{ item.task_complete}}</li>
    <li>{{ item.created}}</li>
    <li>
      <a href="{% url 'UpdateTodoTask' pk=item.pk %}">Update</a>
    </li>
    <li>
      <a href="{% url 'DeleteTodoTask' pk=item.pk %}">Delete</a>
    </li>
    {% endfor %}
  </ul>
  {% endblock %}

Django/todo_2/addTodo/templates/addTodo/update_confirmation.html
{% extends 'addTodo/base.html' %}
{% block title %}Update List{% endblock %}

{% block content %}

  <h1>Update List</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Save List</button>
  </form>

  <a href="{% url 'lists' %}">Back to Lists</a>

{% endblock %}